name = "kiasusaver"
account_id = "1a3a9e03a1e5e708bd1b5a022f9484c3"
workers_dev = true
main = "server/entry.cloudflare-pages.js"
compatibility_date = "2025-06-05"

[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB"
database_name = "kiasu-saver-local"
database_id = "e57f0e68-7f6c-4e2a-bc3b-f94c84c48095"
preview_database_id = "e57f0e68-7f6c-4e2a-bc3b-f94c84c48095"

[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "kiasu-saver-dev"
database_id = "ac4c3375-557e-4c96-9cef-4c86584a69c8"

[env.stg]
[[env.stg.d1_databases]]
binding = "DB"
database_name = "kiasu-saver-stg"
database_id = "stg-kiasusaver"

[env.prod]
[[env.prod.d1_databases]]
binding = "DB"
database_name = "kiasu-saver-prod"
database_id = "84c01d44-b78c-425d-8b5a-0239d7f0b16e"
